### ISSUE TITLE
Does this skip already downloaded Clips?

### ISSUE THREAD

**Issue by styler2go** [HugoJF/twitch-clip-downloader#10]
Is it possible to have an option to skip clips which already exist on the filesystem?

**Comment by HugoJF** [comment]
This is not implemented yet, but is planned. I don't really have the time to implement this since I'm dedicated to other projects.

**Comment by HugoJF** [comment]
This has been implemented in commit 5e7f7e43b340016898d92ac5b2224c645b19e5e1.

This tool also takes care of incomplete downloads (643a5ae73e9d52bdb8f8c85e19fcfe28272aaaf7), to avoid them being detected as a downloaded clip.

Sorry it took this long.
