### ISSUE TITLE
don't work?

### ISSUE THREAD

**Issue by xMeftu** [HugoJF/twitch-clip-downloader#2]
Hello, i have problem.

I create ttv app, add client id like 6x13o4tm3h7vypndoxh******** and when i run script:

✔ What channel do you want to download clips from? … nameofchannel
⠋ Paginating API, please wait...No client id specified

i run DEBUG=TRUE, create more twitch app's and still problem.

**Comment by HugoJF** [comment]
Make sure you are running using `npm run start`, without it, `dotenv` will not be loaded. 

Check if your CLIENT_ID is set on `.env` and not `.env.example`

**Comment by xMeftu** [comment]
OK, next problem:
`⠸ Paginating API, please wait...Error while fetching clips [code 410]: Gone
this API has been removed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clips-downloader@1.0.0 start: `node -r dotenv/config index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clips-downloader@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-09T19_07_54_174Z-debug.log
`
debug.log:

> 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle clips-downloader@1.0.0~prestart: clips-downloader@1.0.0
7 info lifecycle clips-downloader@1.0.0~start: clips-downloader@1.0.0
8 verbose lifecycle clips-downloader@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle clips-downloader@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle clips-downloader@1.0.0~start: CWD: /root
11 silly lifecycle clips-downloader@1.0.0~start: Args: [ '-c', 'node -r dotenv/config index.js' ]
12 silly lifecycle clips-downloader@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle clips-downloader@1.0.0~start: Failed to exec start script
14 verbose stack Error: clips-downloader@1.0.0 start: `node -r dotenv/config index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:315:20)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:315:20)
14 verbose stack     at maybeClose (internal/child_process.js:1051:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
15 verbose pkgid clips-downloader@1.0.0
16 verbose cwd /root
17 verbose Linux 4.4.0-165-generic
18 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
19 verbose node v14.4.0
20 verbose npm  v6.14.5
21 error code ELIFECYCLE
22 error errno 1
23 error clips-downloader@1.0.0 start: `node -r dotenv/config index.js`
23 error Exit status 1
24 error Failed at the clips-downloader@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

>

**Comment by xMeftu** [comment]
version npm: npm@6.14.5

**Comment by HugoJF** [comment]
@xMeftu Sorry, that was a really stupid error, TLDR: found an error on `thedist/Twitch_API_v5`, fixed directly on `node_modules`, forgot about that.

Just released a cruddy new API implementation with the help of #1 to fix this.

Please let me know if this fixed it for you.

**Comment by HugoJF** [comment]
Since the creation of this issue, the tool pretty much got rewritten. If you encounter any new problems, feel free to create a new issue!
