### ISSUE TITLE
Unhandled YoutubeDL error forcing application to break

### ISSUE THREAD

**Issue by Dunkstormen** [HugoJF/twitch-clip-downloader#29]
Been playing around and have run into this problem multiple times. When downloading clips I would run into an unhandled error from YoutubeDL (See attached image for the exact error). Whenever this happens, it forces the application to exit. After digging through the code it seems that there is nothing setup to catch the error thrown by YoutubeDL. Perhaps this is in the making?

I've checked the URL the error is referring, and can watch the clip without issues.

![image](https://user-images.githubusercontent.com/7177605/103565217-3aac7480-4ec0-11eb-9a57-55347c0b30de.png)

**Comment by HugoJF** [comment]
Fixed in 26e11f262be813c935a7254497cb51d91cb2b63a.
