### ISSUE TITLE
Default Export not found in Clip-Url-Fetcher.ts

### ISSUE THREAD

**Issue by paulsoniat** [HugoJF/twitch-clip-downloader#40]
After running npm install and npm run start I get the following error 

![image](https://user-images.githubusercontent.com/30808043/122799900-edfb0100-d287-11eb-8d9b-a078a74dca2b.png)

Any suggestions on how to fix would be appreciated. It seems that it is not properly finding the default import for youtubedl.ts in clip-url-fetcher.ts

**Comment by HugoJF** [comment]
Do you mind sharing what happened?

Since you closed I assume it was something on your end but maybe I can improve the documentation somehow to avoid this from happening again.
