### ISSUE TITLE
Output to file list

### ISSUE THREAD

**Issue by camjac251** [HugoJF/twitch-clip-downloader#7]
I want to archive a channel but it's showing 56,000 available clips and I'm worried it might take up more space than I physically have available to download. Could it be possible to export a file list instead of downloading directly through the app in youtube-dl? I was hoping to manually run youtube-dl so it can skip ones that already exist but it would need to crawl everytime with twitch-clip-downloader.

**Comment by HugoJF** [comment]
I'm not really sure if I'm understanding correctly, can you describe exactly what your problem is? From your description I can imagine 3 problems you might be having:

1. Skip already downloaded clips, that way you can stop and resume the downloads at a later date;
2. Manually filter clips;
3. Split the download location into multiple storage devices.

Which one better describes your situation?

**Comment by camjac251** [comment]
I was hoping that I could end up with a file list export of all of the clip URLs on new lines.
I was able to make something myself by running the script in debug mode and logging the output to a file like `npm run start > streamername.txt`, then I'd sort the lines in my text editor and copy all of the
```
      url: 'https://clips.twitch.tv/RandomWordsHere',
```
to a new file, and remove `url: '` and `',` but it's a lot of work.

Could it be possible for the script to extract the url field from all of the json entries it pulls and just output that to a text file like
```
https://clips.twitch.tv/RandomWordsHere
https://clips.twitch.tv/WordsRandomHere
https://clips.twitch.tv/HereRandomWords
https://clips.twitch.tv/RandomHereWords
```


I noticed that the youtube-dl that the node module calls uses python2.7 for some reason and it seems a bit slower than the python3 counterpart. Running youtube-dl manually myself with a file list like `youtube-dl -a "streamerclips.txt" --write-info-json` would work better for me I think.

**Comment by HugoJF** [comment]
> Running youtube-dl manually myself with a file list like youtube-dl -a "streamerclips.txt" --write-info-json would work better for me I think.

This is what I'm trying to understand. The tool uses `youtube-dl` to download clips, why do you want to use it directly?

I have no problem adding this feature, if you really want it, but I want to provide a better/direct solution for this problem.

**Comment by camjac251** [comment]
If the script can export a list then I could always stop and start `youtube-dl` since it's using that list to download from. If I use `twitch-clip-downloader` though, since it's not cached it will use the API every time to grab a new list of clips. I'm hoping to resume from where I left off and doing it all manually makes it easier that way.

**Comment by HugoJF** [comment]
How doing this manually makes it easier? I can easily add a check to avoid re-downloading clips.

Would that fix your problem?

**Comment by camjac251** [comment]
For my case, I was hoping to do it separately. It would only need a way to generate a text file containing a list of clip urls being exportable.

**Comment by HugoJF** [comment]
Everything that's returned by Twitch's API is now written to a file `<channel-name>.meta` in a JSON format once it finishes the API pagination phase. Details: 2520ca061b95350d14f8f89a7c1a65ea7eb27629
